#' Read, recode and check
#'
#' @description
#' This is a simple function for reading, recoding, and performing some checks on a data file. This function does not recode pedigree data.
#'
#' @param datObj data frame with data after a consistency analysis
#' @param local data file path
#' @param s field/column separator
#' @param d decimal point used in data file
#' @param h logical value indicating presence of header in data file
#' @param missData missing data indicator
#' @param colsPdg identification of columns related to pedigree data
#' @param colsTrts identification of columns related to traits
#' @param colsDts identification of columns related to Dates
#'
#' @details
#' The rrcData function reads data from a file and stores it in a data frame.
#' Otherwise, it uses the data object provided by the user via the datObj argument. The first
#' action of the function recodes the environmental effects, or more generally, the effects
#' which were not indicated as being associated with pedigree, traits, or date. After that, it
#' It is then checked whether all characters in the data object are ASCII and whether the recoded values are all
#' positive, if the integers are less than or equal to 2,147,483,647, and if the variances are within
#' the interval 1E-5 to 1E5. Failure in any of these checks stops the function.
#'
#' The first two checks aim to guarantee that common requirements for genetic evaluation
#' softwares are met. Checking whether the integer values are greater than the presented
#' value ensures that data can be processed by multiple genetic evaluations softwares.
#' The final check aims to prevent numerical problems in iterative processes,
#' which are typically used in genetic analyses.
#'
#' This function is usually not used directly since its results are intermediate and
#' are mainly used for other functions, such as rrcDataPed and fw. However, it
#' can be used to check and re-code environmental effects when there is no
#' interest in pedigree. If pedigree data exists, pass the returned data frame
#' to the rrcPed function to replace the original codes with the new ones
#' generated by the latter function.
#'
#' @returns a data frame with data file columns read and recoded as needed.
#'
#' @examples
#' # Creating data
#' data<-data.frame(id = paste0("i", 1:5), sire = paste0("s", c(rep(1, 2), rep(2, 2), 3)),
#' dam = paste0("d", 1:5), cg = gl(n = 2, k = 2, length = 5, labels = c("gc1", "gc2")),
#' bwd = as.Date(c("2014-10-02", "2014-02-15", "2017-06-30", "2017-06-14", "2016-07-01"), format = "%Y-%m-%d"),
#' trt1 = rnorm(5, 2, 2), trt2 = rnorm(5, 10, 3))
#' data
#'
#' # Recoding and checking data
#' # All data must pass the checks and the cg colum must be recoded
#' rcData<-rrcData(datObj = data, colsPdg = 1:3, colsTrts = 6:7, colsDts = 5)
#' rcData
#'
#' @export
#'
#'

rrcData<-function(datObj = NULL, colsPdg = NULL, colsTrts = NULL, colsDts = NULL,
                  local = NULL, s = " ", d = ".", h = FALSE, missData = c(""," ","NA")){

  #Validation
  argTest<-as.character(sum(!is.null(local), !is.null(datObj)))
  switch(argTest,
         '0' = stop("You must provide EXACTLY ONE of the following arguments:\n",
                  "-'local': path to the file (character)\n",
                  "-'datObj': R object (data.frame)\n",
                  "Both cannot be NULL at the same time", call. = FALSE),

         '2' = stop("You must provide ONLY ONE of the following arguments:\n",
                  "-'local': path to the file (character)\n",
                  "-'datObj': R object (data.frame)\n",
                  "Both cannot be provided simultaneously", call. = FALSE))

  if(is.null(local) == FALSE){
    #Data reading
    tipo<-stringr::str_extract(local,"(\\w+)$")
    if(tipo == basename(local)){
      tipo<-"txt"
    }
    if(stringr::str_detect(local,"https://docs.google.com/spreadsheets")){
      tipo<-"gsheet"
    }
    switch(tipo,
           csv = dados<-utils::read.csv(local, header = h, sep = s, dec = d,
                                        strip.white = FALSE, na.strings = missData, fill = TRUE),

           xls = dados<-as.data.frame(readxl::read_excel(local, na = missData, col_names = h)),

           xlsx = dados<-as.data.frame(readxl::read_excel(local, na = missData, col_names = h)),

           ods = dados<-as.data.frame(readODS::read_ods(local, na = missData, col_names = h)),

           gsheet = {googlesheets4::gs4_auth()
             dados<-as.data.frame(googlesheets4::read_sheet(local, na = missData),
                                  col_names = h)},

           txt = dados<-utils::read.table(local, header = h, sep = s, dec = d,
                                          strip.white = FALSE, na.strings = missData, fill = TRUE),

           print("I did not detect the type of the file.")
    )
  }else{
    dados<-as.data.frame(datObj)
    print(dados)
  }

  ##########
  #Recoding#
  ##########
  for(i in 1:length(dados)){
    if(all(i != c(colsPdg, colsTrts, colsDts))){
      tempData<-unique(dados[[i]])
      codes<-1:length(tempData)
      mapa<-data.frame(tempData, codes)
      names(mapa)<-c("Original.Codes", "Recode")
      index<-match(dados[[i]],mapa$Original.Codes)
      dados[,i]<-mapa$Recode[index]
    }
  }

  #Checking if the characters are ASCII
  dadosTemp<-NULL
  dadosTemp<-sapply(dados, paste0, collapse = " ")
  stopifnot(all(grepl("^[ -~]+$", dadosTemp)))

  #checking if all recoded values are positive
  effects<-as.data.frame(dados[,-c(colsTrts, colsPdg, colsDts)])
  for(i in 1:length(effects)){
    if(any(effects[,i] < 0)){
      stop("All values should be positive.")
    }
  }

  #Checking if the integers are within limits
  if(any(effects > 2147483647)){
    stop("Effects values are too big.")
  }

  #Checking if variances of traits are within a reasonable interval
  if(!is.null((colsTrts))){
    varTemp<-sapply(as.data.frame(dados[, colsTrts]), function(x){stats::var(x, na.rm = TRUE)})
    if(any(varTemp < 1e-5 | varTemp > 1e5)){
      warning("Variances of the traits are too small ou too big. You should scale the data.")
    }
  }
  dados
}
